/**
 * Server Side Rendering
 */
import { APIGatewayEvent, Context } from "aws-lambda";
import * as React from "react";
import { renderToString } from "react-dom/server";

import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";
import App from "../App";

type IContextRender = Context & {
  password: any;
};

/**
 * Server-side rendering
 */
export default async function render(_event: APIGatewayEvent, _context?: IContextRender): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  config.uuid = _context?.password;
  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <App />
    </ConfigContext.Provider>,
  );
  return html({ stats, content, config });
}
