# Generated by Django 4.0.4 on 2022-05-23 01:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security_app', '0003_alter_sharer_limit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='code',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='limit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 22, 53, 4, 176260)),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
