# Generated by Django 4.0.4 on 2022-05-23 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0005_alter_sharer_limit_datetime_alter_sharer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='limit_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 22, 54, 55, 541553)),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
