# Generated by Django 4.0.4 on 2022-05-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security_app', '0009_alter_sharer_limit_datetime_alter_sharer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
