# Generated by Django 4.0.4 on 2022-05-26 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0010_alter_sharer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='limit_datetime',
            field=models.DateField(default=datetime.date(2022, 6, 2)),
        ),
    ]
