openapi: "3.0.1"
info:
  title: "totvs_password"
  version: "2023-04-17 14:31:03UTC"
servers:
- url: "https://0tdsqbv6xd.execute-api.sa-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /userPassValidator:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Default response for ANY /userPassValidator"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:sa-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:sa-east-1:099529297084:function:userPassValidator/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"

