# Generated by Django 4.0.5 on 2022-06-03 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=30, null=True)),
                ('data_expiracao', models.DateField()),
                ('visualizacao_max', models.IntegerField()),
                ('qtd_visualizacao', models.IntegerField()),
            ],
        ),
    ]
