# Generated by Django 4.0.4 on 2022-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('maximum_views', models.IntegerField()),
                ('visualized', models.IntegerField()),
                ('ips', models.ManyToManyField(to='generator.ip')),
            ],
        ),
    ]
