# Generated by Django 4.0.4 on 2022-05-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ip', models.CharField(max_length=39)),
            ],
        ),
        migrations.RenameField(
            model_name='password',
            old_name='visualized',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='password',
            name='ips',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.AddField(
            model_name='access',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.password'),
        ),
    ]
