# Generated by Django 4.0.4 on 2022-05-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_access_rename_visualized_password_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='password',
            new_name='passwd',
        ),
    ]
