# Generated by Django 4.0.4 on 2022-05-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_rename_password_password_passwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='passwd',
            new_name='value',
        ),
    ]
