# Generated by Django 4.0.4 on 2022-05-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_rename_passwd_password_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
