# Generated by Django 4.0.4 on 2022-05-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_password_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='id',
            new_name='identification',
        ),
    ]
