# Generated by Django 4.0.4 on 2022-05-24 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_rename_id_password_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='identification',
            new_name='id',
        ),
    ]
