# Generated by Django 4.0.4 on 2022-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_remove_password_identification_password_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
