# Generated by Django 4.0.5 on 2022-06-04 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='data_expiracao',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
