# Generated by Django 4.0.5 on 2022-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_password_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='data_expiracao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='qtd_visualizacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='visualizacao_max',
            field=models.IntegerField(null=True),
        ),
    ]
