# Generated by Django 4.0.5 on 2022-06-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_password_data_expiracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='data_expiracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='qtd_visualizacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='visualizacao_max',
            field=models.IntegerField(),
        ),
    ]
