# Generated by Django 4.0.5 on 2022-06-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_password_data_expiracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='data_expiracao',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='qtd_visualizacao',
            new_name='max_views',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='visualizacao_max',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='password',
            name='senha',
        ),
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
